### ISSUE TITLE
[BUG] Error downloading Figma Server Render Data

### ISSUE THREAD

**Issue by SangTVArcherGame** [simonoliver/UnityFigmaBridge#21]
After Click Sync document, I can not download data from my Figma document. Then, Unity popup text "Error downloading Figma Server Render Data".
Do you meet the popup and how do you deal it? 

** Version**
 - Unity Version: Unity 2021.3.4f1
 - Platform Windows 10
 - Rendering Pipeline built- in renderer pipeline

**Comment by simonoliver** [comment]
Hey @SangTVArcherGame - you probably have run into an issue where Figma is trying to render images that are too large (I'll put in a catch for this in the future). For now can you try changing "Server Render Image Scale" in the settings to 1 and try again?

**Comment by simonoliver** [comment]
I'd be happy to take a look - are you able to share a link to the Figma file here?

**Comment by SangTVArcherGame** [comment]
Sure, this is my Figma file
https://www.figma.com/file/Bu3dnUzwlPx7po8zB0HWQL/%5BBU%5D-Archer-UI-game-(Copy)?type=design&node-id=24%3A102&t=tcy9s6QwFaPpYg5I-1

Thanks

**Comment by simonoliver** [comment]
I've had a look, and the reason its currently failing is because there are so many "server render" images - a total of 650. Taking a look, it seems that there are many copies of some icons rather than instances of components, so they are rendered many times (as in the screenshot)

![Screenshot 2023-06-01 093819](https://github.com/simonoliver/UnityFigmaBridge/assets/1059515/7f2baedf-9181-4646-8e29-c892d5bf9f34)

If you replaces these copies with components, it should download few images and import ok (like in attached image)

![Screenshot 2023-06-01 093925](https://github.com/simonoliver/UnityFigmaBridge/assets/1059515/2d638a08-fcac-4f80-92b5-0db23a0d4ad2)

**Comment by simonoliver** [comment]
Hey - I just implemented batching for the server render image system so it should now work with any number of images. If you update the package to the latest and try again, your Figma file should now work fine.

**Comment by SangTVArcherGame** [comment]
Yeahhhh, thank you for your best support. I am going to try and feed back to you.

**Comment by SangTVArcherGame** [comment]
> Hey - I just implemented batching for the server render image system so it should now work with any number of images. If you update the package to the latest and try again, your Figma file should now work fine.
