### ISSUE TITLE
Server rendering does not take stroke into account for size of rendered image

### ISSUE THREAD

**Issue by kamunimaximus** [simonoliver/UnityFigmaBridge#8]

**Comment by simonoliver** [comment]
@kamunimaximus  Could you explain this with an example? The stroke is rendered properly here in my examples (eg here, stroke width is set to 1 and 10 for the two circles and seems to work just fine)
![StrokeWidth](https://user-images.githubusercontent.com/1059515/222148325-74a20235-5c7a-475d-bc69-34a972517b13.png)

**Comment by kamunimaximus** [comment]
![image](https://user-images.githubusercontent.com/5563544/222920366-4e7b4111-184c-435b-b73a-9d526efe91fa.png)
![image](https://user-images.githubusercontent.com/5563544/222920375-50a0720c-fe05-4832-a9d6-3298aeb6e5d4.png)
When rendering text the size of the generated image is not increased to fit the stroke if it is outside

**Comment by simonoliver** [comment]
This should now be fixed in latest commit. You'll need to make sure that the borders of the objects are set correctly though as it will only render within  those.
(Previous)
![Screenshot 2023-03-09 144419](https://user-images.githubusercontent.com/1059515/224065495-1d52f469-1f4a-408d-942f-82d4059ab46d.png)
(Now)
![Screenshot 2023-03-09 150112](https://user-images.githubusercontent.com/1059515/224065578-629ca1c7-c82b-42b8-bed7-e209bc3cfaf6.png)

@kamunimaximus Can you let me know if this addresses the issue?
